- type: job
  id: SCPMTFMedic
  name: Медик МОГ
  description: Держать отряд в боеспособном состоянии, оттаскивать трупы за баррикады, закидываться эфедрином и бежать с автоматом на араву Повстанцев Хаоса.
  playTimeTracker: JobSCPMTFMedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: JobSCPMTFMedic
      time: 18000
  startingGear: SCPMTFMedicGear
  icon: "JobIconSCPMTFMedic"
  overrideConsoleVisibility: false
  supervisors: Командиру МОГ, Лейтенанту МОГ, Сержанту МОГ
  canBeAntag: false
  access:
  - SCPMTFMedic
  - SCPMTFOperative
  - Security
  - Armory
  - Brig
  - Detective
  - Cryogenics
  - ChiefMedicalOfficer
  - Medical
  - Chemistry
  accessGroups:
  - SCPFoundationStaff
  - SCPFoundationSecurity
  special:
  - !type:AddComponentSpecial

- type: startingGear
  id: SCPMTFMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMTFSCP
    id: SCPIDCardMTF_Medic
    ears: ClothingHeadsetMTF
    pocket1: EmergencyMedipen
