- type: department
  id: ChaosInsurgency
  name: Неизвестная Группировка
  description: НГ
  color: "#0c344d"
  roles:
  - SCPNGCommander
  - SCPNGLieutenant
  - SCPNGSergeant
  - SCPNGMedic
  - SCPNGEngineer
  - SCPNGOperative
  weight: 10
  primary: True

- type: department
  id: SCPFoundationMTF
  name: Мобильная Оперативная Группа
  description: МОГ
  color: "#0a54e7"
  roles:
  - SCPMTFCommander
  - SCPMTFLieutenant
  - SCPMTFSergeant
  - SCPMTFMedic
  - SCPMTFEngineer
  - SCPMTFOperative
  weight: 50
  primary: True

- type: department
  id: SCPFoundationDirector
  name: Руководство Комплекса
  description: Р
  color: "#334E6D"
  roles:
  - SCPManager
  - SCPHOS
  - SCPHead_of_the_zone
  weight: 40

- type: department
  id: SCPFoundationSecurity
  name: Охрана Комплекса
  description: ОК
  color: "#DE3A3A"
  weight: 30
  roles:
  - SCPHOS
  - SCPWarden
  - SCPSecuritySergeant
  - SCPSecurity


- type: department
  id: SCPFoundationStaff
  name: Персонал Комплекса
  description: П
  color: "#9FED58"
  weight: 20
  roles:
  - SCPHead_of_the_zone
  - SCPEngineer
  - SCPSenior_scientist
  - SCPScientist
  - SCPJanitor
  primary: True

# Дополнительные департаменты вне списка
# Мобильный оперативная группа
- type: department
  id: JobSCPMTFCommander
  name: Командир МОГ
  description: Мобильная оперативная группа фонда SCP
  color: "#003DCA"
  roles:
  - SCPMTFCommander
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPMTFLieutenant
  name: Лейтенант МОГ
  description: Мобильная оперативная группа фонда SCP
  color: "#0096FF"
  roles:
  - SCPMTFLieutenant
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPMTFSergeant
  name: Сержант МОГ
  description: Мобильная оперативная группа фонда SCP
  color: "#0096FF"
  roles:
  - SCPMTFSergeant
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPMTFMedic
  name: Медик МОГ
  description: Мобильная оперативная группа фонда SCP
  color: "#70C3FF"
  roles:
  - SCPMTFMedic
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPMTFEngineer
  name: Инженер МОГ
  description: Мобильная оперативная группа фонда SCP
  color: "#70C3FF"
  roles:
  - SCPMTFEngineer
  weight: 10
  editorHidden: true

# Неизвестная группировка (Повстанцы хаоса)
- type: department
  id: JobSCPNGCommander
  name: Командир ПХ
  description: Повстанцы хаоса
  color: "#006826"
  roles:
  - SCPNGCommander
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPNGLieutenant
  name: Лейтенант ПХ
  description: Повстанцы хаоса
  color: "#0D7D35"
  roles:
  - SCPNGLieutenant
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPNGSergeant
  name: Сержант ПХ
  description: Повстанцы хаоса
  color: "#0D7D35"
  roles:
  - SCPNGSergeant
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPNGMedic
  name: Медик ПХ
  description: Повстанцы хаоса
  color: "#008F1C"
  roles:
  - SCPNGMedic
  weight: 10
  editorHidden: true

- type: department
  id: JobSCPNGEngineer
  name: Инженер ПХ
  description: Повстанцы хаоса
  color: "#008F1C"
  roles:
  - SCPNGEngineer
  weight: 10
  editorHidden: true

#Персонал

- type: department
  id: JobSCPEngineer
  name: Инженер Камер Содержания
  description: Инженер Камер Содержания
  color: "#af8790"
  roles:
  - SCPEngineer
  weight: 10
  editorHidden: true