- type: job
  id: MilitaryMainMedic
  name: Старший военный врач
  description: Проведение сложных операций, клонирование или реанимация убитых морпехов, лечение и реабилитация раненых, варка лекарств и стимуляторов.
  playTimeTracker: JobMilitaryMainMedic
  startingGear: MilitaryMainMedicGear
  icon: "JobIconMilitaryMainMedic"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  accessGroups:
    - MedicalOfficer
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: MilitaryMainMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackCMOFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLabCmo
    ears: ClothingHeadsetCMO
    id: MilitaryMainMedicIDCard
    belt: ClothingBeltMedicalFilled
    pocket1: EmergencyMedipen
