- type: job
  id: SCPJanitor
  name: Уборщик Класс-J
  description: Вы – работник фонда, отвечающий за научную/исследовательскую деятельность, так или иначе, вы служите фонду и подчиняетесь тем кто выше вас по должности.
  playTimeTracker: JobSCPJanitor
  startingGear: SCPJanitorGear
  icon: "JobIconSCPJanitor"
  supervisors: Научному персоналу, Охране комплекса, Командованию комплекса
  canBeAntag: false
  access:
  - SCPJanitor
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: SCPJanitorGear
  equipment:
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatOrangesoft
    jumpsuit: ClothingUniformJumpsuitSCPDCLASS
    id: SCPIDCardJanitor
    back: ClothingBackpackSatchelSalvage
    belt: ClothingBeltJanitorFilled
    shoes: ClothingShoesGaloshes
    pocket2: RMCPouchLargeDropFilled
