- type: job
  id: BravoMedic
  name: Командир отряда "Браво"
  description: job-description-bravomedic
  playTimeTracker: JobBravoMedic
  startingGear: BravoMedicGear
  icon: "JobIconBravoMedic"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - SquadBravoMedic
  special:
  - !type:AddComponentSpecial



- type: startingGear
  id: BravoMedicGear
  equipment:
    jumpsuit: UGEJumpsuitMarineBravo
    id: BMedicIDCard
    pocket1: EmergencyMedipen
