- type: job
  id: BravoEngineer
  name: Инженер отряда "Браво"
  description: Держаться поближе к отряду, поддерживать укреплениями морпехов. Открывать двери и шлюзы, строить оборонительные пункты.
  playTimeTracker: JobBravoEngineer
  startingGear: BravoEngineerGear
  icon: "JobIconBravoEngineer"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadBravo
    - Engineering
    - Maintenance
  special:
  - !type:AddComponentSpecial


- type: startingGear
  id: BravoEngineerGear
  equipment:
    jumpsuit: UGEJumpsuitEngineer
    id: BEngineerIDCard
    pocket1: EmergencyMedipen
